module.exports = { '0': { id: 'DELETED', detail: undefined },
  '1': { id: 'DUPLICATE_CONTENT', detail: undefined },
  '2': { id: 'RATELIMITED', detail: undefined },
  '3': { id: 'AUTH_FAIL', detail: undefined },
  '4': { id: 'APPLICATION_RATELIMITED', detail: undefined },
  '5': { id: 'CONNECTION_FAIL', detail: undefined },
  '6': { id: 'INVALID_STATE', detail: undefined },
  DELETED: { id: 0, detail: undefined },
  DUPLICATE_CONTENT: { id: 1, detail: undefined },
  RATELIMITED: { id: 2, detail: undefined },
  AUTH_FAIL: { id: 3, detail: undefined },
  APPLICATION_RATELIMITED: { id: 4, detail: undefined },
  CONNECTION_FAIL: { id: 5, detail: undefined },
  INVALID_STATE: { id: 6, detail: undefined } };